language: node_js
node_js:
- '0.12'
- '0.10'
env:
  global:
    secure: cYmW+LsZhD/b+7Mw46AL0WwGsTHCAFSj7AaL5hq4gv+q/zhLgpMPoLKiaV7zGwsDXWti4vcKhTHG4DTpMwJV0/cTZR3sm+N0XM7ChnD3M37vakMFcoehDCqrVNJ5ZbUyNTYVLHmPWL/jCw2D7/hSB6ri7HxXpVKxNXRMl4d5nYMaMkL9hBMP6VrwZ/sS9JnXx1udTb0WV4T0v8gJ82Aig56hTEgy1MpeWM89wAQRdTOHuGNOvrdzV5mpFtxOnswfq7XH0FkIxUJ9hae3Y0KnJaBN+lDWMWxRpA/aoVnA2vK2EUFXTBxkqEWJPDw8LXu+K3HtxRZqlJ6F7uQwTei0ZO8S4xPe6Cs0znQedl8r7pYpSSlgCPU+TZvWqG/Z3PBoJ2kfMQWfhvEjjUVU3GXG0/vh7qxCmR255NjNsyJDk2b/KsD5kmUJJYi/O2si5LXNfiJ4mTubUmiIYArvRaK+2bVYjSxxBb44ox958z1enZvT7exKEEJE8MYVMluFh/7zdwXoAtzTEUcTRQXyHFCNpo7dhmV18NX/YJBrskBvdtTYeH9aRv7Ued8fJGancapYZv4hLJ6m23H6REwXnn3udhfQ9IxI4jMP1tA9K8DcqcT8sf3MGx6HOIi+lmlEqrGVgKwmMRAjW+kmSw1PA2o/VZ/PaP2txgFqI7uAyqR/h2w=
